import numpy as np
x = np.random.randn(20,1)
print(x)
#print("Average of the array elements:")
#mean = x.mean()
#print(mean)
print("Standard deviation of the array elements:")
std = x.std()
print(std)
print("Variance of the array elements:")
var = x.var()
print(var)
